name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Release version
        required: true

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
    - name: validate Rust
      run: make rust-version
    - name: Format
      run: make format
    - name: Lint
      run: make lint
    - name: Test
      run: make test
    - name: Build
      run: make release
    - name: Publish Binary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.version }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag}" \
            --generate-notes
    - name: Add Download Badge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.version }}
      run: |
        sed -i "1s;^;[![CI/CD Pipeline](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/CICD.yml/badge.svg) ![Download Latest](https://img.shields.io/badge/Download%20Latest-$tag-blue.svg)](https://github.com/${GITHUB_REPOSITORY}/archive/refs/tags/$tag.zip)\n\n;" README.md
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add README.md
        git commit -m "Update Download badge for version $tag"
        git push